services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: keyboard_assembly_system
    ports:
      - 6000:5432
  admin-bot-redis:
    image: redis:latest
    ports:
      - 6379:6379
  customer-bot-redis:
    image: redis:latest
    ports:
      - 6380:6379
  employee-bot-redis:
    image: redis:latest
    ports:
      - 6381:6379
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_PASS: 123
      RABBITMQ_DEFAULT_USER: test
