create table admins (telegram_id bigint not null, username varchar(255), primary key (telegram_id));
create table cases (price float(53) not null, id bigint generated by default as identity, name varchar(255), primary key (id));
create table customers (telegram_id bigint not null, username varchar(255), primary key (telegram_id));
create table customers_orders (customer_id bigint not null, orders_id bigint not null unique);
create table employee_orders (employee_id bigint not null, order_id bigint not null unique);
create table employees (approved boolean not null, username varchar(255), telegram_id bigint not null, primary key (telegram_id));
create table keyboards (case_id bigint, id bigint generated by default as identity, keycap_id bigint, switch_id bigint, primary key (id));
create table keycaps (price float(53) not null, id bigint generated by default as identity, name varchar(255), primary key (id));
create table orders (id bigint generated by default as identity, customer_telegram_id bigint not null, employee_telegram_id bigint, keyboard_id bigint unique, readiness_state varchar(255) check (readiness_state in ('CREATED','IN_PROGRESS','COMPLETED','CANCELLED')), primary key (id));
create table switches (price float(53) not null, id bigint generated by default as identity, name varchar(255), primary key (id));
alter table if exists customers_orders add constraint FK_orders_id_orders foreign key (orders_id) references orders;
alter table if exists customers_orders add constraint FK_customer_id_customers foreign key (customer_id) references customers;
alter table if exists employee_orders add constraint FK_order_id_orders foreign key (order_id) references orders on delete cascade;
alter table if exists employee_orders add constraint FK_employee_id_employees foreign key (employee_id) references employees on delete cascade;
alter table if exists keyboards add constraint FK_case_id_cases foreign key (case_id) references cases on delete cascade;
alter table if exists keyboards add constraint FK_keycap_id_keycaps foreign key (keycap_id) references keycaps on delete cascade;
alter table if exists keyboards add constraint FK_switch_id_switches foreign key (switch_id) references switches on delete cascade;
alter table if exists orders add constraint FK_customer_id_customers foreign key (customer_telegram_id) references customers on delete cascade;
alter table if exists orders add constraint FK_employee_id_employees foreign key (employee_telegram_id) references employees on delete set null;
alter table if exists orders add constraint FK_keyboard_id_keyboards foreign key (keyboard_id) references keyboards on delete cascade;

insert into admins (telegram_id, username)
values (820137077, '@drilltseptsovofficial');
